package com.neu.cloud.cloudApp.model;

import java.util.Date;
import java.util.UUID;

import jakarta.persistence.*;

@Entity
@Table(name = "verification_info")
public class VerificationInfo {

    @Id
    @GeneratedValue(generator = "UUID")
    private UUID id;

    @Column(name = "username", unique = true)
    private String username;

    @Column(name = "email_exp_time")
    @Temporal(TemporalType.TIMESTAMP)
    private Date emailExpTime;

    public VerificationInfo() {
        // Adding 2 minutes to the current time for the email sent time
        this.emailExpTime = new Date(System.currentTimeMillis());
    }

    // Assume getters and setters are generated by Lombok

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Date getEmailExpTimeTime() {
        return emailExpTime;
    }

    public void setEmailExpTimeTime(Date emailExpTime) {
        this.emailExpTime = emailExpTime;
    }
}
