name: GCP Image Creation

on:
  push:
    branches: [main]

jobs:
  build_gcp_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.CSYE6225CSYE }}
          project_id: csye6225csye
          export_default_credentials: true

      - name: Install Packer
        run: |
          sudo apt-get update && sudo apt-get install packer

      - name: Build GCP Image with Packer
        run: |
          packer init .
          packer validate .
          packer build -var 'project_id=csye6225csye' -var 'zone=us-east1-b' cent.pkr.hcl
        env:
          GCP_PROJECT_ID: csye6225csye
          GCP_ZONE: us-east1-a  # Example zone, adjust as needed
          SOURCE_IMAGE: projects/centos-cloud/global/images/family/centos-stream-8
          MACHINE_TYPE: n1-standard-1  # Example machine type, adjust as needed
