# This file contains the GitHub Actions workflow for creating a new GCP VM image 
# using Packer when changes are pushed to the main branch.

name: Create GCP Image

on:
  push:
    branches: [main]
    
jobs:

  build_gcp_image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
          java-version: '17'
          distribution: 'adopt'
      
    - name: Build with Maven
      run: mvn clean package -DskipTests
        
    - name: Set up Google Cloud SDK 
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.CSYE6225CSYE }}
        project_id: csye6225csye
        export_default_credentials: true
        
    - name: Create Instance Template
      run: |  
        cd packer
        packer init .
        packer build -var 'artifact_path=${{ github.workspace }}/target/cloud-app-0.0.1-SNAPSHOT.jar' -var 'project_id=csye6225csye' -var 'zone=us-east1-b' cent.pkr.hcl
        
    - name: Configure MIG to use new template
      run: gcloud compute instance-groups managed set-instance-template INSTANCE_GROUP_NAME --template=INSTANCE_TEMPLATE_NAME
        
    - name: Re-create MIG instances
      run: gcloud compute instance-groups managed recreate-instances INSTANCE_GROUP_NAME
      
    - name: Wait for instance refresh
      run: |
        gcloud compute instance-groups managed wait-until --stable INSTANCE_GROUP_NAME
